apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
    - name: "81"
      port: 81
      targetPort: 81
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
