apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
    - name: "3000"
      port: 3000
      targetPort: 3000

  selector:
    io.kompose.service: mongo
  type: NodePort
status:
  loadBalancer: {}
